### ISSUE TITLE
Slow Performance on camelCaseProperty

### ISSUE THREAD

**Issue by tgohn** [robinweser/css-in-js-utils#13]
Hi 👋 

## Context

While measuring our React app using `fela` and `react`, I notice that we are is spending quite a sizeable JS time in `camelCaseProperty`

This screenshot is taken using Chrome JS perf tool:

<img width="732" alt="Screenshot 2020-08-04 at 5 02 42 PM" src="https://user-images.githubusercontent.com/6629569/89275470-e41ede00-d674-11ea-8c60-6b03770fb8ce.png">

The screenshot shows that `camelCaseProperty` is one of the top functions in term of.`Self Time`

## Findings

In `fela` project, after https://github.com/robinweser/fela/pull/707/files#diff-bb4e560677b8345d9f60eb8b414b9c99R245, we are effectively calling `camelCaseProperty()` for each style declaration on each React component re-rendering.

This could means a lot of function calls if the React app is triggering re-rendering excessively

**Suggestion:**
Similar to [hyphenate-style-name](https://github.com/rexxars/hyphenate-style-name/blob/e5400abe204407d36364ffec21b00a62ca676c45/index.js#L11), let's add a simple cache to stored processed style property in `camelCaseProperty`
It should, in effect, reduce the number of function calls to `camelCaseProperty`.

If you are okay with this approach, I can make a PR for this as well. Thank you.

---
Other related issues:
https://github.com/robinweser/css-in-js-utils/pull/11/files

**Comment by robinweser** [comment]
Hey there! Thanks for the issue.
So, we already recognized the perf implications from `camelCaseProperty` and decided to remove it altogether in the next version. See https://github.com/robinweser/fela/pull/803

But as it'll still be used in certain scenarios and other plugins etc. I'd still love to have that cache available - so if you're still up to send a PR, I'd really appreciate that!

**Comment by tgohn** [comment]
Thanks @robinweser 

I made a PR on https://github.com/robinweser/css-in-js-utils/pull/14.
Hopefully it can be released as a minor/patch update to `css-in-js-utils` version. So current `fela` version would benefit from this change.
